### ISSUE TITLE
Demo 1 doesn't work on Safari 9.1.1

### ISSUE THREAD

**Issue by ppazos** [dperini/nwxforms#11]
tried this https://dl.dropboxusercontent.com/u/598365/html5forms/html5forms.html and the form gets submitted without validation.

**Comment by dperini** [comment]
Sorry for the delayed answer ...
the problem was only on Dropbox examples, the "nwxforms.js" resource script was not loaded due to different folder layout. However I have already fixed that on Dropbox. 
I also included a minor 1 byte change that was already committed on GitHub (related to a non correctly escaped regex).
